project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu:
          - text: Hands-on Exercise 0 (Introduction to Quarto)
            href: Hands-on_Ex0.qmd
          - text: Hands-on Exercise 1.1 (Geospatial Data Wrangling with R)
            href: Hands-on_Ex1/Hands-on_Ex1.qmd
          - text: Hands-on Exercise 1.2 (Chloropleth Mapping with R)
            href: Hands-on_Ex1/Hands-on_Ex2.qmd
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1 (Spatial Weights and Applications)
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    backgroundcolor: '#ffc5c0'
    theme: journal
    css: styles.css
    toc: true

editor: visual

