project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu:
          - text: Hands-on Exercise 0 (Introduction to Quarto)
            href: Hands-on_Ex0.qmd
          - text: Hands-on Exercise 1.1 (Geospatial Data Wrangling with R)
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1-1.qmd
          - text: Hands-on Exercise 1.2 (Chloropleth Mapping with R)
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1-2.qmd
          - text: Hands-on Exercise 2 (Global and Local Measures of Spatial Autocorrelation)
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.qmd
          - text: Hands-on Exercise 3 (Geographical Segmentation with Spatially Constrained Clustering Techniques)
            href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.qmd
          - text: Hands-on Exercise 4 (Calibrating Hedonic Pricing Model with GWR Method)
            href: Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4.qmd
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1 (Spatial Weights and Applications)
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.qmd
          - text: In-class Exercise 2 (Do functionally similar water points positively co-occur in Nigeria?)
            href: In-class_Ex/In-class_Ex2/In-class_Ex2.qmd
          - text: In-class_Exercise 3 (Spatially Constrainted Clustering with ClustGeo)
            href: In-class_Ex/In-class_Ex3/In-class_Ex3.qmd
      - text: Take-home Exercises
        menu:
          - text: Take-home Exercise 1 (Geospatial Analytics for Social Good)
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    backgroundcolor: '#fec0ce'
    theme: pulse
    css: styles.css
    toc: true
    code-fold: show
    code-overflow: wrap
    code-tools:
      source: true
      toggle: true
      caption: none
    code-summary: "Press to toggle code"
editor: visual

